
const GITHUB_AUTH_TOKEN = ""
const GITHUB_USERNAME = "Daham1234"
const SESSION_ID = "𝙰𝚂𝙸𝚃𝙷𝙰-𝙼𝙳=DyAF3LIB#4FPHvnH4LZ00ZdujU7p-AYdFD7MUTVBK5VcBH4Rr9BM"


module.exports = {
GITHUB_AUTH_TOKEN,
GITHUB_USERNAME,
SESSION_ID
}
